spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: booking-service
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/v1/booking/**
        - id: location-service
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/api/v1/location/**
        - id: location-ws
          uri: lb://LOCATION-SERVICE
          predicates:
            - Path=/ws/**

#  main:
#    web-application-type: reactive


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: ${GEOTRIP_SECRET_KEY}
