spring:
  application:
    name: APIGatewayService
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: booking-service
          uri: lb://BOOKINGSERVICE
          predicates:
            - Path=/api/v1/booking/**
        - id: location-service
          uri: lb://LOCATIONSERVICE
          predicates:
            - Path=/api/v1/location/**

#  main:
#    web-application-type: reactive


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

jwt:
  secret: ${GEOTRIP_SECRET_KEY}
